### ISSUE TITLE
Error	MSB3644

### ISSUE THREAD

**Issue by nyendwa** [Keboo/XAMLTest#156]
I tried to run this project (https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit) I came across the error below let me know if I jumped in too early for this project.

Error	MSB3644	The reference assemblies for .NETFramework,Version=v4.6.2 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. 
You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks	
MaterialDesignColors.Wpf	
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	1229

**Comment by Keboo** [comment]
Hi @nyendwa this is not directly related to this project.

The reason for your failure is the MaterialDesignInXamlToolkit is built [targeting several versions on .NET](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/MaterialDesignThemes.Wpf.csproj#L4) to allow people to use it in a variety of applications. If you want to compile it from source, you will either need to install the relevant .NET frameworks (typically from the Visual Studio Installer or newer frameworks [here](https://learn.microsoft.com/dotnet/core/install/windows?tabs=net70)), or you can edit the various `<TargetFrameworks>` elements in the projects to just have the framework(s) that you care about.

**Comment by nyendwa** [comment]
I am using a latest .NET 7 framework. Should it still give me challenges to
run it?

**Comment by Keboo** [comment]
If you use the NuGet package in your app, no it should just work. But if you try to compile the code locally, it requires having all of the needed frameworks that the library targets (because when compiling it needs to build all the targets that the NuGet suports). 
There is also more information on the Wiki. https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Compiling-From-Source
