### ISSUE TITLE
Add methods to support performing double clicks

### ISSUE THREAD

**Issue by Keboo** [Keboo/XAMLTest#193]
Right now the mixins have convenience methods for clicking, but it would be convenient to have one that performed a double click.

you can see the current click implementation here:
https://github.com/Keboo/XAMLTest/blob/master/XAMLTest/VisualElementMixins.Input.cs#L55-L77

Please add a new SendDoubleClick method similar the one above that performs the click twice. As well and a LeftDoubleClick method that is similar to the LeftClick method. https://github.com/Keboo/XAMLTest/blob/master/XAMLTest/VisualElementMixins.Input.cs#L27-L39

Ensure a test is written as well.

**Comment by blouflashdb** [comment]
I would like to work on this. Can you assign this issue to me please?

**Comment by Keboo** [comment]
Done. Let me know if you have any questions on it.

**Comment by blouflashdb** [comment]
I am not sure what kind of tests I should write in SendMouseInputTests.

**Comment by Keboo** [comment]
I would write a test similar to this one (you can do it in that same class too).
(https://github.com/Keboo/XAMLTest/blob/master/XAMLTest.Tests/SendMouseInputTests.cs#L63-L80).

The basic steps would be:
- Register for the `Control.MouseDoubleClickEvent` event.
- Execute your new method
- Assert that the event was raised

**Comment by blouflashdb** [comment]
I cannot get a proper test code for the LeftDoubleClick method to work as the test setup is very hard for me to understand and I cannot debug the test. I am using VSCode with the C# Dev Kit.

**Comment by Keboo** [comment]
What operating system are you running under? Because this is a WPF UI testing library, it will only be able to execute under a Windows environment. 

As for the test, something like this should work:
```C#
    [NotNull] 
    private static IVisualElement<Button>? Button { get; set; } 
 
    [ClassInitialize] 
    public static async Task ClassInitialize(TestContext context) 
    { 
        App = await XamlTest.App.StartRemote(logMessage: context.WriteLine); 
         
        await App.InitializeWithDefaults(Assembly.GetExecutingAssembly().Location); 
 
        var window = await App.CreateWindowWithContent($""" 
        <Grid x:Name="Grid" Background="Transparent" Margin="10"> 
            <Grid.RowDefinitions> 
                <RowDefinition Height="Auto" /> 
                <RowDefinition /> 
            </Grid.RowDefinitions> 
            <Grid.ContextMenu> 
                <ContextMenu> 
                    <MenuItem Header="Context1" x:Name="Context1" /> 
                </ContextMenu> 
            </Grid.ContextMenu> 
            <Menu>  
                <MenuItem Header="TopLevel" x:Name="TopLevel"> 
                    <MenuItem Header="SubMenu" x:Name="SubMenu" /> 
                </MenuItem> 
            </Menu> 
         
            <Button Content="Click Me" Grid.Row="1" VerticalAlignment="Center" HorizontalAlignment="Center"/> 
        </Grid> 
        """); 
        Grid = await window.GetElement<Grid>("Grid"); 
        TopMenuItem = await window.GetElement<MenuItem>("TopLevel"); 
        Button = await window.GetElement<Button>(); 
    } 
 
 ....
 
     [TestMethod] 
    public async Task CanDoubleClickOnGrid() 
    { 
        await using var recorder = new TestRecorder(App); 
 
        await using IEventRegistration registration = await Button.RegisterForEvent(nameof(Control.MouseDoubleClick)); 
        await Button.LeftDoubleClick(); 
 
        await Wait.For(async () => 
        { 
            var invocations = await registration.GetInvocations(); 
            Assert.AreEqual(1, invocations.Count); 
        }); 
 
        recorder.Success(); 
    } 
```

**Comment by blouflashdb** [comment]
Thanks, I got the test to work with this setup. The reason I did not got it to work before was because I used RegisterForEvent on the Menu.
