### ISSUE TITLE
GRPC Exception

### ISSUE THREAD

**Issue by HClausing** [Keboo/XAMLTest#65]
Congratulations for this nice project. It's very helpfull, and I didn't find any other for WPF UI / Styles / Templates testing.

I'm trying to setup here , but I'm getting a GRPC exception for every action after StartRemote. Here's my base test implementation:

```
using NUnit.Framework;
using FluentAssertions;
using System.Threading.Tasks;
using XamlTest;

namespace EficazFramework.Tests
{
    public class BaseTest
    {
        internal static IApp Application { get; private set; }
        internal static IWindow MainWindow { get; private set; }

        public BaseTest()
        {
            if (Application == null)
                Application = XamlTest.App.StartRemote<EficazFramework.Tests.WPF.Views.App>();
        }

        [OneTimeSetUp]
        public async Task Setup()
        {
            if (MainWindow == null)
                MainWindow = await Application.GetMainWindow();

        }

    }
}
```

Result when trying to get the Main Window:
`OneTimeSetUp: Grpc.Core.RpcException : Status(StatusCode="Unavailable", Detail="failed to connect to all addresses")`

I really don't know what I'm doing wrong. Should I call Application.Initialize() ? I didn't understand exaclty if it should be called when using .StartRemote<T>.

NOTE: I also tried without the static modifier, and got the same result.

Thanks

**Comment by Keboo** [comment]
A couple quick questions. First, which version of the library are you using? 
If it was one of the early 1.0.0 preview builds, it is possible that failure was due to a VS debugger feature failure. I have attempted a fix in #67. If you could test any build **after** `1.0.0-ci235` and let me know if it is fixed that would be great.

**Comment by HClausing** [comment]
It worked!

Thank you so much!

**Comment by HClausing** [comment]
Oh sorry. I'll need to reopen the issue.

This time I figured that the first attempt is failing with this GRPC Exception. It happens on Azure DevOps Pipelines also.

**Comment by Keboo** [comment]
No problem. I appreciate the feedback. The `StartRemote` method contains a `logMessage` parameter. Can you try supplying it with something like this and let me know if anything is added to the `StringBuilder`?

```C#
StringBuilder sb = new StringBuilder();
Action<string> logMessage = message => sb.AppendLine(message);
XamlTest.App.App.StartRemote<EficazFramework.Tests.WPF.Views.App>(logMessage: logMessage);
```

**Comment by HClausing** [comment]
Tried this way. But I can't reproduce anymore. 

After add the log and stringBuilder it didn't get exception anymore. Confusing.

I'll keep this closed until it starts to happen again.

Thanks.

**Comment by HClausing** [comment]
Finally I reproduced the error again. But only on Azure Pipelines.

Unfortunatelly it's not logging anything on logMessage action.

**Comment by HClausing** [comment]
This is the full stack trace:

```
   em GrpcDotNetNamedPipes.NamedPipeChannel.CreateConnectionContext[TRequest,TResponse](Method`2 method, CallOptions callOptions, TRequest request)
   em GrpcDotNetNamedPipes.NamedPipeChannel.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions callOptions, TRequest request)
   em Grpc.Core.Interceptors.InterceptingCallInvoker.<AsyncUnaryCall>b__4_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   em Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.AsyncUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, AsyncUnaryCallContinuation`2 continuation)
   em Grpc.Core.Interceptors.InterceptingCallInvoker.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   em XamlTest.Host.Protocol.ProtocolClient.GetMainWindowAsync(GetWindowsQuery request, CallOptions options)
   em XamlTest.Host.Protocol.ProtocolClient.GetMainWindowAsync(GetWindowsQuery request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken)
   em XamlTest.Internal.App.<GetMainWindow>d__15.MoveNext()
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   em EficazFramework.Tests.BaseTest.<OneTimeSetup>d__25.MoveNext() em E:\Henrique Clausing\Repositorios\Current\EficazFramework\src\Tests\Desktop\EficazFramework.Tests.WPF\BaseTest.cs:linha 40
```

**Comment by Keboo** [comment]
Great. Thank you. I am working on getting a little more logging and configuration added in (that I hope will address this). 
Just in terms of an overview of what is happening. When you call `App.StartRemote` it starts a new XAMLTest.exe process passing in the information about your WPF assembly. It starts up its own WPF application shell, then invokes your main method (unless you have customized it, it will be the one generated by WPF). As part of the App Startup event, it starts up a GRPC server, which the original test process connects to (this appears to be the connection that is failing). 

I suspect that the XAMLTest.exe process that is starting up, is either failing to start (possibly crashing), or simply taking longer than expected making the test connection timeout. 

I do have PR #70 in the works that exposes control of the connection timeout and it is possible simply increasing this amount will solve the problem. Conveniently, some of the tests are now failing with the same issue. So I am looking into why that is happening.

**Comment by HClausing** [comment]
I figured on my machine, that a second test try works fine. 

On Azure Pipelines it fails all the time.

I would like to help more, but I'm very novice with GRPC.

**Comment by Keboo** [comment]
I just pushed version `XAMLTest.1.0.0-ci249`. When you get a little time would you mind testing to see if it resolves your issue?

**Comment by HClausing** [comment]
For sure.

After  6 runs (1 on my machine and last 5 on Azure Pipelines), I guess It's working.

Just one run on Azure have failed. 

Nice job. Many thanks.
